use crate::assets::mapper::AssetMetadata;
use std::collections::HashMap;

/// Get 4-cost (Overlord/Calamity) echo mappings
/// Format: (filename, name, element, class, cost, tags)
fn get_overlord_echoes() -> Vec<(&'static str, &'static str, &'static [&'static str], &'static str, u8, &'static str, &'static str, &'static str, u8)> {
    vec![
        //Jinzhou
        ("330000040.webp", "Lampylumen Myriad", &["Freezing Frost"], "Overlord", 4, "Transform into Lampylumen Myriad. Perform up to 3 consecutive attacks. Unleash a freezing shock by performing consecutive forward strikes, with the initial two strikes inflicting 200.16% and 200.16% Glacio DMG respectively, and the final strike dealing 266.88% Glacio DMG. Enemies will be frozen on hit. Each shock increases the current character’s Glacio DMG by 4.00% and Resonance Skill DMG dealt by 4.00% for 15s, stacking up to 3 times.", "", "", 20),
        ("330000020.webp", "Inferno Rider", &["Molten Rift"], "Overlord", 4, "Transform into Inferno Rider to launch up to 3 consecutive slashes in a row, each slash dealing 242.40%, 282.80%, and 282.80% Fusion DMG respectively. After the final hit, increase the current character’s Fusion DMG by 12.00% and Basic Attack DMG by 12.00% for 15s. Long press the Echo Skill to transform into Inferno Rider and enter the Riding Mode. When exiting the Riding Mode, deal 282.80% Fusion DMG to enemies in front.", "", "", 20),
        ("330000190.webp", "Nightmare: Inferno Rider", &["Molten Rift"], "Overlord", 4, "Transform into Nightmare: Inferno Rider and jump to attack enemies in front, dealing 405% Fusion DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Fusion DMG Bonus and 12.00% Resonance Skill DMG Bonus.", "Hold Echol Skill to transform into Nightmare: Inferno Rider and enter Riding Mode. When exiting Riding Mode, deal 283.50% Fusion DMG to enemies in front.", 25),
        ("340000080.webp", "Thundering Mephis", &["Void Thunder"], "Overlord", 4, "Transform into Thundering Mephis, engaging in a rapid assault of up to 6 strikes. The first 5 strikes deal 132.61% Electro DMG each, while the final strike inflicts 189.44% Electro DMG, with an additional 31.57% Electro DMG from the thunder. After the final hit, increase the current character’s Electro DMG by 12.00% and Resonance Liberation DMG by 12.00% for 15s.", "", "", 20),
        ("330000010.webp", "Tempest Mephis", &["Void Thunder"], "Overlord", 4, "Transform into Tempest Mephis to perform tail swing attacks followed by a claw attack. The lightning strike summoned by the tail swing deals 102.48% Electro DMG each time, while the claw attack deals 175.68% Electro DMG. After the claw hit, increase the current character’s Electro DMG by 12.00% and Heavy Attack DMG by 12.00% for 15s.", "", "", 20),
        ("330000160.webp", "Nightmare: Thundering Mephis", &["Void Thunder"], "Overlord", 4, "Transform into Nightmare: Thundering Mephis and attack enemies in front, dealing 405% Electro DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Electro DMG Bonus and 12.00% Resonance Liberation DMG Bonus", "", 25),
        ("330000140.webp", "Nightmare: Feilian Beringal", &["Sierra Gale"], "Overlord", 4, "Summon a Nightmare: Feilian Beringal to attack enemies, dealing 164.16% Aero DMG. The remaining Whirlwind Beam will continuously attack surrounding enemies up to 5 times, each dealing 21.89% Aero DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Aero DMG Bonus and 12.00% Heavy Attack DMG Bonus.", "", 20),
        ("330000050.webp", "Feilian Beringal", &["Sierra Gale"], "Overlord", 4, "Transform into Feilian Beringal to perform a powerful kick. If the kick lands on an enemy, immediately perform a follow-up strike. The kick deals 231.84% Aero DMG, and the follow-up strike deals 283.36% Aero DMG. After the follow-up strike hits, the current character's Aero DMG increases by 12.00%, and the Heavy Attack DMG increases by 12.00% for 15s.", "", "", 20),
        ("6000059.webp", "Jué", &["Celestial Light"], "Calamity", 4, "Summon Jué to the aid. Jué soars through the air, dealing 48.64% Spectro DMG, and summons thunderbolts that strike nearby enemies up to 5 times, each hit dealing 19.46% Spectro DMG. Jué then spirals downward, attacking surrounding enemies twice, each hit dealing 48.64% Spectro DMG. Casting this Echo Skill grants the Resonator a Blessing of Time effect that lasts 15s, during when:", "- The Resonator gains 16% Resonance Skill DMG Bonus.", "- When the Resonator's Resonance Skill hits the target, inflict 16% Spectro DMG 1 time per second for 15s, considered as the Resonator's Resonance Skill DMG. ", 20),
        ("330000060.webp", "Mourning Aix", &["Celestial Light"], "Overlord", 4, "Transform into Mourning Aix and perform 2 consecutive claw attacks, each attack dealing 157.44% and 236.16% Spectro DMG respectively. After the transformation, increase current character's Spectro DMG by 12.00% and Resonance Liberation DMG by 12.00% for 15s.", "", "", 20),
        ("340000070.webp", "Dreamless", &["Havoc Eclipse"], "Calamity", 4, "Transform into Dreamless and perform 6 consecutive attacks. The first 5 attacks deal 54.08% Havoc DMG each, and the last attack deal 270.40% Havoc DMG. The DMG of this Echo Skill is increased by 50% during the first 5s after Rover-Havoc casts Resonance Liberation.", "", "", 20),
        ("340000010.webp", "Crownless", &["Havoc Eclipse"], "Overlord", 4, "Transform into Crownless and perform up to 4 consecutive attacks. The first 2 attacks deal 134.08% Havoc DMG each, the 3rd attack deals 100.56% Havoc DMG 2 times, and the 4th attack deals 67.04% Havoc DMG 3 times. After the transformation, increase current character's Havoc DMG by 12.00% and Resonance Skill DMG by 12.00% for 15s.", "", "", 20),
        ("330000180.webp", "Nightmare: Crownless", &["Havoc Eclipse"], "Overlord", 4, "Transform into Nightmare: Crownless and attack enemies in front, dealing 264.6% Havoc DMG. The Resonator with this Echo equipped in their main slot gains 12.00% Havoc DMG Bonus and 12.00% Basic Attack DMG Bonus.", "This skill has 3 initial charges, replenished once every 12s, max 3 charges. When Nightmare: Crownless hits a target, DMG dealt by this skill is increased by 20.00%. This effect lasts for 2s and does not stack.", "", 12),
        ("6000060.webp", "Fallacy of No Return", &["Rejuvenating Glow"], "Overlord", 4, "Activate the Echo Skill to summon a fraction of the Fallacy of No Return's power and deal a blast to the surrounding area, inflicting Spectro DMG equal to 15.86% of max HP, after which the Resonator gains 10% bonus Energy Regen and all team members 10% bonus ATK for 20s.", "Hold Echo Skill to unleash a series of flurry assaults at the cost of STA, each dealing Spectro DMG equal to 1.58% of max HP; Release to end the assail in a powerful blow, dealing Spectro DMG equal to 19.82% of max HP.", "", 20),
        ("340000020.webp", "Bell-Borne Geochelone", &["Rejuvenating Glow","Moonlit Clouds"], "Calamity", 4, "Activate the protection of Bell-Borne Geochelone. Deal Glacio DMG based on 145.92% of the current character's DEF to nearby enemies, and obtain a Bell-Borne Shield that lasts for 15s The Bell-Borne Shield provides 50.00% DMG Reduction and 10.00% DMG Boost for the current team members, and disappears after the current character is hit for 3 times.", "", "", 20),
        ("330000030.webp", "Impermanence Heron", &["Moonlit Clouds"], "Overlord", 4, "Transform into Impermanence Heron to fly up and smack down, dealing 310.56% Havoc DMG. Long press to stay as Impermanence Heron Heron and continuously spit flames, each attack dealing 55.73% Havoc DMG. Once the initial attack lands on any enemy, the current character regains 10 Resonance Energy. If the current character uses their Outro Skill within the next 15s, the next character’s damage dealt will be boosted by 12% for 15s.", "", "", 20),
        ("340000060.webp", "Mech Abomination", &["Lingering Tunes"], "Overlord", 4, "Strike the enemies in front, dealing 48.64% Electro DMG. Summon Mech Waste to attack enemies. Mech Waste deals 320% Electro DMG on-hit and explode after a while to deal 160% Electro DMG. After casting this Echo Skill, increase current character's ATK by 12.00% for 15s. Damage dealt by Mech Waste is considered Outro Skill DMG.", "", "", 20),

        //Rinascita
        ("340000100.webp", "Hecate", &["Freezing Frost","Molten Rift","Void Thunder","Sierra Gale","Celestial Light","Havoc Eclipse","Empyrean Anthem"], "Calamity", 4, "Summon 3 twirling Crescent Servants around you. Crescent Servants attack enemies with their spinning blades, dealing 45.59% Havoc DMG. Triggering a Counterattack with the Echo attacks extends the Crescent Servants’ duration.", "The Resonator with this Echo equipped in the main slot has their Coordinated Attack DMG increased by 40.00%.", "", 20),
        ("330000170.webp", "Nightmare: Tempest Mephis", &["Void Thunder","Empyrean Anthem"], "Overlord", 4, "Transform into Nightmare: Tempest Mephis and attack surrounding enemies, dealing 405% Electro DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Electro DMG Bonus and 12.00% Resonance Skill DMG Bonus.", "", 25),
        ("330000120.webp", "Sentry Construct", &["Frosty Resolve"], "Overlord", 4, "Transform into Sentry Construct and attack enemies in front, dealing 405% Glacio DMG. Each time the Resonator with this Echo casts Resonance Liberation, it charges the Strike Capacitor. Once Strike Capacitor is at max level, the Echo Skill cooldown will be reset.", "Use Echo Skill to transform into Sentry Construct and dive into enemies from the air, dealing 405% Glacio DMG and freezing the target.", "The Resonator with this Echo equipped in their main slot gains 12.00% Glacio DMG Bonus and 12.00% Resonance Skill DMG Bonus.", 25),
        ("6000105.webp", "Nightmare: Lampylumen Myriad", &["Frosty Resolve","Empyrean Anthem"], "Overlord", 4, "Summon a Nightmare: Lampylumen Myriad and attack nearby enemies, dealing 273.60% Glacio DMG. The Resonator with this Echo equipped in their main slot gains 12.00% Glacio DMG Bonus and has their Coordinated Attack DMG increased by 30.00%.", "", "", 20),
        ("330000200.webp", "Nightmare: Mourning Aix", &["Eternal Radiance"], "Overlord", 4, "Summon a Nightmare: Mourning Aix to attack surrounding enemies, dealing 273.60% Spectro DMG. DMG dealt to enemies inflicted by Spectro Frazzle is increased by 100.00%.", "The Resonator with this Echo equipped in their main slot gains 12.00% Spectro DMG Bonus.", "", 20),
        ("330000110.webp", "Lorelei", &["Midnight Veil"], "Overlord", 4, "Transform into Lorelei and attack surrounding enemies, dealing 405% Havoc DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Havoc DMG Bonus and 12.00% Basic Attack DMG Bonus.", "", 25),
        ("330000150.webp", "Nightmare: Impermanence Heron", &["Midnight Veil"], "Overlord", 4, "Transform into Nightmare: Impermanence Heron and deliver up to 10 consecutive strikes to surrounding enemies, each dealing 40.50% Havoc DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Havoc DMG Bonus and 12.00% Heavy Attack DMG Bonus.", "", 25),
        ("330000130.webp", "Dragon of Dirge", &["Tidebreaking Courage"], "Overlord", 4, "Transform into Dragon of Dirge and summon a Grief Rift lasting for 5s. Periodically deal 36.81% Fusion DMG to enemies within the area of effect.", "The Resonator with this Echo equipped in the main slot gains 12.00% Fusion DMG Bonus and 12.00% Basic Attack DMG Bonus.", "", 25),
        ("6000106.webp", "Reminiscence: Fleurdelys", &["Gusts of Welkin","Windward Pilgrimage"], "Calamity", 4, "Summon the Windcleaver to attack the target, dealing 27.36% Aero DMG 8 times and 136.80% Aero DMG once. The Resonator with this Echo equipped in their main slot gains 10.00% Aero DMG Bonus. If this Resonator is Rover: Aero or Cartethyia, grant another 10.00% Aero DMG Bonus.", "", "", 20),
        ("6000113.webp", "Nightmare: Kelpie", &["Gusts of Welkin","Windward Pilgrimage"], "Overlord", 4, "Transform into Nightmare: Kelpie to attack nearby targets, dealing 405% Glacio DMG. The Resonator with this Echo equipped in the main slot gains 12.00% Glacio DMG Bonus and 12.00% Aero DMG Bonus. Switching out the Resonator with Outro Skill summons Nightmares: Kelpie to deal 405.00% Aero DMG.", "", "", 25),
        ("6000114.webp", "Lioness of Glory", &["Flaming Clawprint"], "Overlord", 4, "Summon the Halberd of Glory to crush an area, dealing 82.08% Fusion DMG to nearby targets, and then blast off after a short delay, dealing 191.52% Fusion DMG. The Resonator with this Echo equipped in the main slot gains 12.00% Fusion DMG Bonus and 12.00% Resonance Liberation DMG Bonus.", "", "", 20),
        ("6000115.webp", "Nightmare: Hecate", &["Dream of the Lost"], "Calamity", 4, "Transform into Nightmare: Hecate. Leap up and smash down, dealing 3 stages of damage, each dealing Havoc DMG equal to 152.39% of her ATK. The Resonator with the Echo equipped in the main slot gains 12.00% Havoc DMG Bonus and 20.00% Echo Skill DMG Bonus.", "", "", 25),
        ("6000116.webp", "Reminiscence: Fenrico", &["Dream of the Lost, Law of Harmony"], "Overlord", 4, "Summon the Talons of Decree to attack nearby enemies, dealing 273.60% Aero DMG. The Resonator with this Echo equipped in their main slot gains 12.00% Aero DMG Bonus and 12.00% Heavy Attack DMG Bonus.", "", "", 20),
        ("6000160.webp", "Lady of the Sea", &["Crown of Valor"], "Overlord", 4, "Summon a Tidestorm to deal 13.68% Aero DMG ten times and 164.16% Aero DMG one time to enemies. The Resonator with this Echo equipped in the main slot gains 12.00% Aero DMG Bonus and 12.00% Resonance Liberation DMG Bonus.", "", "", 20),
        ("6000121.webp", "The False Sovereign", &["Crown of Valor"], "Overlord", 4, "Transform into the False Sovereign and dash forward in a spinning strike, dealing 55.35% Electro DMG 4 times. The Resonator with this Echo equipped in the main slot gains 12.00% Electro DMG Bonus and 12.00% Heavy Attack DMG Bonus. Upon casting Intro Skill, the False Sovereign is also summoned to deal 405.00% Electro DMG. Start with 2 charges. Gain 1 charge every 8s, up to 2 charges.", "", "", 8),
        ("6000167.webp", "Reminiscence: Threnodian - Leviathan", &["Flamewing's Shadow, Thread of Severed Fate"], "Calamity", 4, "Summon a Collapsing Horizon, dealing two instances of 131.04% Havoc DMG to the nearby enemies and obtaining the Core of Collapse for 15s. While it lasts, Core of Collapse deals 24.57% Havoc DMG when the active Resonator in the team deals damage. This effect can be triggered once every 0.5s, up to 8. Enemies with Havoc Bane take 100% more DMG from this effect. The Resonator with this Echo equipped in the main slot gains 12% Havoc DMG Bonus and 12% Resonance Liberation DMG Bonus.", "", "", 25),
       
        // Lahrai-Roi
        ("6000190.webp", "Reactor Husk", &["Halo of Starry Radiance"], "Overlord", 4, "Transform into Reactor Husk, jumping into the air and unleashing a heavy slash that deals 351% Fusion DMG to enemies.", "The Resonator with this Echo equipped in their main slot gain 10.00% Energy Regen.", "", 20),
        ("6000189.webp", "Hyvatia", &["Pact of Neonlight Leap", "Rite of Gilded Revelation"], "Overlord", 4, "Summon Hyvatia in mid-air to fire lasers at enemies, dealing 27.36% Spectro DMG 10 times.", "Casting Outro Skill within 15s after summoning Hyvatia grants 10.00% All-Attribute DMG Bonus to the Intro Skill of the incoming Resonator for 15s.", "", 20),

    ]
}

/// Get 3-cost (Elite) echo mappings
fn get_elite_echoes() -> Vec<(&'static str, &'static str, &'static [&'static str], &'static str, u8, &'static str, &'static str, &'static str, u8)> {
    vec![
        //Jinzhou
        ("6000057.webp", "Lumiscale Construct", &["Freezing Frost","Void Thunder"], "Elite", 3, "Transform into a Lumiscale Construct and enter a Parry Stance. If you are not attacked during the Parry Stance, slash to deal 553.6% Glacio DMG when the stance finishes. If attacked, counterattack instantly, dealing 830.4% Glacio DMG. When hit with a Special Skill attack while in the Parry Stance, break the Special Skill and counterattack, dealing 830.4% Glacio DMG. ", "", "", 15),
        ("320000180.webp", "Autopuppet Scout", &["Freezing Frost","Celestial Light"], "Elite", 3, "Transform into Autopuppet Scout, dealing 272% Glacio DMG to the surroundings, and generate up to 3 Ice Walls to block off the enemies. ", "", "", 15),
        ("320000090.webp", "Roseshroom", &["Freezing Frost","Havoc Eclipse"], "Elite", 3, "Summon a Roseshroom that fires a laser, dealing 57.07% Havoc DMG up to 3 times. ", "", "", 15),
        ("320000050.webp", "Tambourinist", &["Freezing Frost","Havoc Eclipse"], "Elite", 3, "Summon a Tambourinist that periodically emits Melodies of Annihilation. Friendly units hit with Melodies of Annihilation deal an extra Havoc DMG of 14.40% with their attacks, up to 10 times. ", "", "", 15),
        ("6000056.webp", "Glacio Dreadmane", &["Freezing Frost","Moonlit Clouds"], "Elite", 3, "Lacerate enemies as a Glacio Dreadmane, dealing 214.4% Glacio DMG on each hit. Equipped with 2 charges and can be cast mid-air. Glacio Dreadmane deals 20% more DMG while in mid-air and generates 6 Icicles upon landing, each dealing 32% Glacio DMG. ", "", "", 20),
        ("320000020.webp", "Violet-Feathered Heron", &["Molten Riftt","Void Thunder"], "Elite", 3, "Transform into Violet-Feathered Heron and enter a Parry Stance. Counterattack when the Parry stance is over, dealing 288% Electro DMG. If attacked during Parry Stance, you can counterattack in advance and additionally recover 5 Concerto Energy.", "", "", 15),
        ("320000100.webp", "Havoc Dreadmane", &["Molten Riftt","Havoc Eclipse"], "Elite", 3, "Transform into Havoc Dreadmane to perform tail strikes up to 2 times. Each strike deals 116.64% Havoc DMG. An additional strike will be performed on hit, dealing 77.76% Havoc DMG. ", "", "", 15),
        ("320000080.webp", "Viridblaze Saurian", &["Molten Riftt","Moonlit Clouds"], "Elite", 3, "Summon a Viridblaze Saurian to continuously spit fire, dealing 17.12% Fusion DMG 10 times.", "", "", 15),
        ("320000040.webp", "Flautist", &["Void Thunder","Lingering Tunes"], "Elite", 3, "Transform into Flautist, continuously emitting Electro lasers, dealing 53.2% Electro DMG for a total of 10 times. Gain 1 Concerto Energy every time a hit lands.", "", "", 15),
        ("320000030.webp", "Cyan-Feathered Heron", &["Sierra Gale","Celestial Light"], "Elite", 3, "Transform into Cyan-Feathered Heron and charge at the enemies, dealing 236.8% Aero DMG; This Echo Skill interrupts enemy Special Skills upon dealing damage.", "", "", 15),
        ("320000110.webp", "Hoochief", &["Sierra Gale","Rejuvenating Glow"], "Elite", 3, "Use the Echo skill, transform into Hoochief Cyclone and attack with a palm, causing 268.2% Aero DMG.", "", "", 15),
        ("320000130.webp", "Carapace", &["Sierra Gale","Moonlit Clouds"], "Elite", 3, "Transform into Carapace to perform a spinning attack that deals 112.00% Aero DMG, followed by a slash that deals 168.00% Aero DMG. ", "", "", 15),
        ("6000058.webp", "Lightcrusher", &["Celestial Light"], "Elite", 3, "Lunge forward as a Lightcrusher, dealing 135.36% Spectro DMG. Generate 6 Ablucence on hit. Each Ablucence explosion deals 15.04% Spectro DMG. Hold the Echo Skill to stay in the Lightcrusher form, which allows you to leap up and pounce forward in the air for a short distance.", "", "", 15),
        ("320000060.webp", "Rocksteady Guardian", &["Celestial Light","Rejuvenating Glow"], "Elite", 3, "Transform into Rocksteady Guardian and enter a Parry State. Upon being attacked, deal Spectro DMG equal to 8.29% of the current character's Max HP, and perform a follow-up attack that deals Spectro DMG equal to 8.29% of the current character's Max HP. Use the Echo skill again to exit the transformation.", "If the attack received is a Special Skill attack, interrupt the enemy's Special Skill and perform a two-stage follow-up attack, each inflicting Spectro DMG equal to 5.52% of the current character's max HP. These follow-up attacks simultaneously launch three ground-breaking waves, each inflicting Spectro DMG equal to 4.59% of the current character's Max HP. ", "", 15),
        ("320000010.webp", "Stonewall Bracer", &["Rejuvenating Glow","Moonlit Clouds"], "Elite", 3, "Transform into Stonewall Bracer and charge forward, dealing 112.64% Physical DMG on-hit, then smash to deal 168.96% Physical DMG, and gain a shield of 10.00% of current character's Max HP. Use the Echo skill again to exit the transformation state.", "", "", 15),
        ("320000070.webp", "Chasm Guardian", &["Rejuvenating Glow","Lingering Tunes"], "Elite", 3, "Transform into Chasm Guardian to perform a Leap Strike that deals 273.60% Havoc DMG on hit. Current character loses 10.00% HP after the hit lands. Periodically restore current character's HP after 5s for up to 10.00% of their Max HP.", "", "", 15),
        ("320000120.webp", "Spearback", &["Moonlit Clouds","Lingering Tunes"], "Elite", 3, "Summon a Spearback to perform 5 consecutive attacks. The first 4 attacks deal 29.96% Physical DMG, and the last deals 51.36% Physical DMG. ", "", "", 15),

        //Rinascita
        ("320000270.webp", "Abyssal Mercator", &["Frosty Resolve","Eternal Radiance"], "Elite", 3, "Transform into Abyssal Mercator and summon 3 Ice Spikes to attack enemies, each dealing 89.39% Glacio DMG.", "", "", 15),
        ("320000300.webp", "Cuddle Wuddle", &["Frosty Resolve","Midnight Veil"], "Elite", 3, "Transform into Cuddle Wuddle and attack enemies with 4 strikes dealing 46.98% Physical DMG and 1 strike dealing 125.28% Physical DMG. ", "", "", 20),
        ("320000220.webp", "Questless Knight", &["Frosty Resolve","Midnight Veil"], "Elite", 3, "Transform into Questless Knight and smash the surrounding enemies, dealing 313.20% Electro DMG.", "", "", 20),
        ("320000250.webp", "Abyssal Patricius", &["Frosty Resolve","Empyrean Anthem"], "Elite", 3, "Transform into Abyssal Patricius and charge forward to attack enemies, dealing 268.20% Glacio DMG.", "The Resonator with this Echo equipped in the main slot gains 12.00% Glacio DMG Bonus.", "", 15),
        ("320000290.webp", "Vitreum Dancer", &["Eternal Radiance","Empyrean Anthem"], "Elite", 3, "Transform into Vitreum Dancer and attack surrounding enemies, dealing 313.20% Electro DMG.", "The Resonator with this Echo equipped in their main slot gains 12.00% Electro DMG Bonus.", "", 20),
        ("320000230.webp", "Diurnus Knight", &["Eternal Radiance","Tidebreaking Courage"], "Elite", 3, "Transform into Diurnus Knight and charge forward to attack enemies with the sword, dealing 268.20% Spectro DMG. DMG dealt to enemies inflicted by Spectro Frazzle is increased by 100.00%.", "", "", 15),
        ("6000096.webp", "Rage Against the Statue", &["Eternal Radiance","Gusts of Welkin","Law of Harmony"], "Elite", 3, "Transform into Rage Against the Statue to attack enemies, dealing 313.20% Spectro DMG. Hold the Echo Skill to maintain the Echo form and charge towards enemies, dealing 469.80% Spectro DMG.", "", "", 20),
        ("6000104.webp", "Capitaneus", &["Eternal Radiance","Gusts of Welkin","Flaming Clawprint","Windward Pilgrimage"], "Elite", 3, "Summon a Capitaneus to jump up and smash enemies, dealing 118.80% Spectro DMG. This attack generates 4 extra Merciless Judgements, each dealing 59.40% Spectro DMG. The Resonator with this Echo equipped in their main slot gains 12.00% Spectro DMG Bonus and 12.00% Heavy Attack DMG Bonus.", "", "", 20),
        ("320000240.webp", "Nocturnus Knight", &["Midnight Veil","Empyrean Anthem"], "Elite", 3, "Transform into Nocturnus Knight and strike enemies in front of you from the air, dealing 268.20% Havoc DMG.", "", "", 15),
        ("320000260.webp", "Abyssal Gladius", &["Midnight Veil","Tidebreaking Courage","Thread of Severed Fate"], "Elite", 3, "Transform into Abyssal Gladius and attack enemies in front of you with the sword, dealing 268.20% Glacio DMG.", "Hold the Echo Skill to maintain the Echo form for a while to slash enemies and cast a ranged attack forward, dealing 268.20% and 670.50% Glacio DMG respectively.", "", 15),
        ("320000280.webp", "Chop Chop", &["Empyrean Anthem","Tidebreaking Courage","Dream of the Lost"], "Elite", 3, "Summon a Chop Chop to perform a series of consecutive attacks. The first 6 strikes each deal 19.26% Fusion DMG and finishing strike deals 77.04% Fusion DMG.", "", "", 15),
        ("320000280_2.webp", "Phantom: Chop Chop", &["Empyrean Anthem","Tidebreaking Courage","Dream of the Lost"], "Elite", 3, "Summon a Chop Chop to perform a series of consecutive attacks. The first 6 strikes each deal 19.26% Fusion DMG and finishing strike deals 77.04% Fusion DMG.", "", "", 15), //hakushin asset
        ("6000097.webp", "Hurriclaw", &["Tidebreaking Courage","Gusts of Welkin","Crown of Valor"], "Elite", 3, "Transform into Hurriclaw and charge forward, dealing 156.60% Aero DMG upon hit plus 156.60% Aero DMG with a sweep attack. Hold the Echo Skill to continue charging forward. Use Echo Skill again while charging to perform a sweep attack.", "", "", 20),
        ("6000120.webp", "Corrosaurus", &["Flaming Clawprint","Flamewing's Shadow"], "Elite", 3, "Summon a Corrosaurus to attack enemies, dealing 273.60% Fusion DMG. The Resonator with this Echo equipped in the main slot gains 12.00% Fusion DMG Bonus and 20.00% Echo Skill DMG Bonus.", "", "", 20),
        ("6000111.webp", "Pilgrim's Shell", &["Flaming Clawprint","Windward Pilgrimage"], "Elite", 3, "Transform into a Pilgrim's Shell to attack nearby enemies, dealing 268.20% Aero DMG.", "", "", 15),
        ("6000112.webp", "Kerasaur", &["Flaming Clawprint","Windward Pilgrimage","Flamewing's Shadow"], "Elite", 3, "Transform into Kerasaur to leap into the air and slam down, dealing 268.20% Aero DMG. Shortly after hitting the target, cast Echo Skill again to charge at the target, dealing 268.20% Aero DMG. The Resonator with this Echo equipped in the main slot gains 12.00% Aero DMG Bonus and 12.00% Resonance Liberation DMG Bonus.", "", "", 15),
        ("6000161.webp", "Nightmare: Violet-Feathered Heron", &["Crown of Valor"], "Elite", 3, "Transform into Violet-Feathered Heron and enter a Parry Stance. Counterattack when the Parry stance is over, dealing 288% Electro DMG. If attacked during Parry Stance, you can counterattack in advance and additionally recover 5 Concerto Energy.", "", "", 15),
        ("6000162.webp", "Nightmare: Cyan-Feathered Heron", &["Law of Harmony"], "Elite", 3, "Transform into Cyan-Feathered Heron and charge at the enemies, dealing 236.80% Aero DMG; This Echo Skill interrupts enemy Special Skills upon dealing damage.", "", "", 15),
        ("6000168.webp", "Nightmare: Viridblaze Saurian", &["Flamewing's Shadow"], "Elite", 3, "Summon a Viridblaze Saurian to continuously spit fire, dealing 17.12% Fusion DMG 10 times. ", "", "", 8),
        ("6000173.webp", "Nightmare: Roseshroom", &["Thread of Severed Fate"], "Elite", 3, "Summon a Roseshroom that fires a laser, dealing 57.07% Havoc DMG up to 3 times.", "", "", 15),
        
        //Lahrai-Roi
        ("6000187.webp", "Frostbite Coleoid", &["Halo of Starry Radiance"], "Elite", 3, "Summon a Frostbite Coleoid to punch enemies, dealing 192.6% Glacio DMG.", "", "", 15),
        ("6000184.webp", "Spacetrek Explorer", &["Halo of Starry Radiance"], "Elite", 3, "Summon a Spacetrek Explorer to grant nearby active Resonators in the team a Shield equal to 10% of the summoner's Max HP for 4s.", "", "", 20),
        ("6000186.webp", "Sabercat Prowler", &["Halo of Starry Radiance", "Pact of Neonlight Leap"], "Elite", 3, "Summon a Sabercat Prowler to fire beams at enemies, dealing 192.6% Havoc DMG.", "", "", 15),
        ("6000185.webp", "Sabercat Reaver", &["Halo of Starry Radiance", "Pact of Neonlight Leap"], "Elite", 3, "Summon a Sabercat Reaver to attack enemies, dealing 192.6% Fusion DMG.", "", "", 15),
        ("6000183.webp", "Ironhoof", &["Pact of Neonlight Leap"], "Elite", 3, "Transform into an Ironhoof to charge at enemies, dealing 53.64% Fusion DMG. At the end of the charge, unleash a goring attack that deals 13.41% Fusion DMG 3 times and 174.33% Fusion DMG once.", "", "", 15),
        ("6000182.webp", "Mining Reindeer", &["Pact of Neonlight Leap"], "Elite", 3, "Summon a Mining Reindeer to launch a charged attack at enemies, dealing 237.6% Electro DMG.", "", "", 20),
        ("6000181.webp", "Flora Reindeer", &["Rite of Gilded Revelation"], "Elite", 3, "Summon a Flora Reindeer to attack enemies within a large range, dealing 192.6% Aero DMG.", "", "", 15),
        ("6000180.webp", "Twin Nova: Collapsar Blade", &["Rite of Gilded Revelation"], "Elite", 3, "Transform into Twin Nova: Collapsar Blade to rapidly fire at enemies for 5s, with each attack dealing 2.01% Electro DMG.", "The Resonator with this Echo equipped in the main slot gains 12.00% Electro DMG Bonus and 12.00% Basic Attack DMG Bonus.", "If Twin Nova: Nebulous Cannon is equipped in another slot on the Resonator: Casting Echo Skill unleashes both Nebulous Cannon and Collapsar Blade skills in quick succession, but is still considered performing the same Echo Skill. DMG dealt by Twin Nova: Collapsar Blade becomes Spectro DMG. The Electro DMG Bonus gained from equipping it in the main slot is turned into Spectro DMG Bonus. Casting Basic Attacks grants 1 stack of Dyad Origins. Casting Resonance Skill grants 3 stacks of Dyad Origins. Dyad Origins can stack up to 6 times and lasts for 8s. Each stack increases Echo Skill DMG by 10%, and all stacks are cleared after this Echo Skill ends. This skill is capped at 2 uses. Initially, this skill can be used 2 times, with 1 use added every 8s.", 8),
        ("6000179.webp", "Twin Nova: Nebulous Cannon", &["Rite of Gilded Revelation"], "Elite", 3, "Transform into a Twin Nova: Nebulous Cannon to slash enemies twice, with each attack dealing 80.51% Spectro DMG.", "The Resonator with this Echo equipped in the main slot gains 12.00% Spectro DMG Bonus and 12.00% Basic Attack DMG Bonus.", "If Twin Nova: Collapsar Blade is equipped in another slot on the Resonator: Casting Echo Skill unleashes both Nebulous Cannon and Collapsar Blade skills in quick succession, but the DMG Bonus from the Echo in the main slot remains unchanged. DMG dealt by Twin Nova: Collapsar Blade becomes Spectro DMG. Casting Basic Attacks grants 1 stack of Dyad Origins. Casting Resonance Skill grants 3 stacks of Dyad Origins. Dyad Origins can stack up to 6 times and lasts for 8s. Each stack increases Echo Skill DMG by 10%, and all stacks are cleared after this Echo Skill ends. This skill is capped at 2 uses. Initially, this skill can be used 2 times, with 1 use added every 8s.", 8),
        ("6000188.webp", "Windlash Coleoid", &["Rite of Gilded Revelation"], "Elite", 3, "Transform into a Windlash Coleoid to kick enemies, dealing 268.2% Aero DMG.", "", "", 15),

    ]
}

/// Get 1-cost (Common) echo mappings
fn get_common_echoes() -> Vec<(&'static str, &'static str, &'static [&'static str], &'static str, u8, &'static str, &'static str, &'static str, u8)> {
    vec![
        //Jinzhou
        ("310000150.webp", "Fusion Prism", &["Freezing Frost","Molten Rift","Lingering Tunes"], "Common", 1, "Summon a Fusion Prism to fire a crystal shard, dealing 32%+64 Fusion DMG.", "", "", 8),
        ("310000190.webp", "Sabyr Boar", &["Freezing Frost","Sierra Gale","Moonlit Clouds"], "Common", 1, "Summon a Sabyr Boar to headbutt the enemy into the air, dealing 32.00%+64 Physical DMG.", "", "", 8),
        ("6000051.webp", "Clang Bang", &["Freezing Frost","Celestial Light"], "Common", 1, "Summon a Clang Bang that follows the enemy and eventually self-combusts, dealing 32.00%+64 Glacio DMG. ", "", "", 8),
        ("310000040.webp", "Glacio Predator", &["Freezing Frost","Celestial Light"], "Common", 1, "Summon a Glacio Predator that throws an ice spear, dealing 46.08% Glacio DMG on hit. Deal 4.61% Glacio DMG up to 10 times during the charging time, and 23.04% Glacio DMG when the spear explodes. ", "", "", 8),
        ("310000120.webp", "Gulpuff", &["Freezing Frost","Celestial Light"], "Common", 1, "Summon a Gulpuff that blows bubbles 5 times, each time dealing 5 Glacio DMG.", "", "", 8),
        ("310000270.webp", "Hoartoise", &["Freezing Frost","Celestial Light"], "Common", 1, "Transform into Hoartoise and slowly restore HP. Use the Echo skill again to exit the transformation state. ", "", "", 2),
        ("310000200.webp", "Excarat", &["Freezing Frost","Havoc Eclipse"], "Common", 1, "Transform into an Excarat and tunnel underground to advance. In this state, you have the ability to change your direction and are immune to damage. ", "", "", 2),
        ("310000140.webp", "Glacio Prism", &["Freezing Frost","Havoc Eclipse","Moonlit Clouds"], "Common", 1, "Summon a Glacio Prism that continuously fires three crystal shards, each dealing 38.40% Glacio DMG.", "", "", 8),
        ("310000030.webp", "Electro Predator", &["Molten Rift","Void Thunder"], "Common", 1, "Summon an Electro Predator to shoot the enemy 5times. The first 4 shots deals 17.28% Electro DMG, and the last deals 46.08% Electro DMG. ", "", "", 8),
        ("310000060.webp", "Fusion Warrior", &["Molten Rift","Void Thunder","Sierra Gale"], "Common", 1, "Transform into Fusion Warrior to perform a Counterattack. If the Counterattack is successful, the cooldown time of this skill will be reduced by 70.00%, and 288% Fusion DMG will be dealt. ", "", "", 15),
        ("310000330.webp", "Traffic Illuminator", &["Molten Rift","Void Thunder","Sierra Gale"], "Common", 1, "Summon a Traffic Illuminator, immobilizing enemies for up to 1s. The immobilization will be lifted once the enemy is hit. ", "", "", 15),
        ("310000160.webp", "Spectro Prism", &["Molten Rift","Void Thunder","Celestial Light"], "Common", 1, "Summon a Spectro Prism to emit a laser that hits the enemy up to 8 times, dealing 14.40% Spectro DMG each time. ", "", "", 8),
        ("310000210.webp", "Baby Viridblaze Saurian", &["Molten Rift","Void Thunder","Lingering Tunes"], "Common", 1, "Transform into Baby Viridblaze Saurian to rest in place, and slowly restore HP.", "", "", 2),
        ("6000054.webp", "Fusion Dreadmane", &["Molten Rift","Rejuvenating Glow"], "Common", 1, "Summon a Fusion Dreadmane that fiercely strikes the enemy, dealing 32%+64 Fusion DMG. ", "", "", 8),
        ("310000080.webp", "Snip Snap", &["Molten Rift","Rejuvenating Glow","Lingering Tunes"], "Common", 1, "Summon a Snip Snap that throws fireballs at the enemy, dealing 32%+64 Fusion DMG on-hit. ", "", "", 8),
        ("6000054.webp", "Lava Larva", &["Molten Rift","Lingering Tunes"], "Common", 1, "Summon a Lava Larva that continuously attacks enemies, dealing 38.4% Fusion DMG with each hit. The Lava Larva disappears when the summoner is switched out or moves too far away. ", "", "", 8),
        ("310000050.webp", "Aero Predator", &["Void Thunder","Lingering Tunes"], "Common", 1, "Summon an Aero Predator that throws a dart forward. The dart will bounce between enemies up to three times, dealing 28.80% Aero DMG each time it hits. ", "", "", 8),
        ("310000170.webp", "Havoc Prism", &["Void Thunder","Celestial Light","Havoc Eclipse"], "Common", 1, "Summon a Havoc Prism to fire five crystal shards, each dealing 23.04% Havoc DMG. ", "", "", 8),
        ("310000020.webp", "Fission Junrock", &["Void Thunder","Rejuvenating Glow","Moonlit Clouds"], "Common", 1, "Summon a Fission Junrock. Generate a Resonance Effect that restores 2% HP for friendly units each time. If not in combat, you can pick up minerals or plants nearby.", "", "", 15),
        ("310000010.webp", "Vanguard Junrock", &["Void Thunder","Rejuvenating Glow","Lingering Tunes"], "Common", 1, "Summon a Vanguard Junrock that charges forward, dealing 32.00%+64 Physical DMG to enemies in its path. ", "", "", 8),
        ("310000130.webp", "Chirpuff", &["Sierra Gale","Havoc Eclipse"], "Common", 1, "Summon a Chirpuff that self-inflates and blasts a powerful gust of wind forward 3 times. Each blast inflicts 3 Aero DMG and pushes enemies backwards. ", "", "", 8),
        ("310000220.webp", "Young Roseshroom", &["Sierra Gale","Havoc Eclipse"], "Common", 1, "Summon a Baby Roseshroom that fires a laser, dealing 32%+64 Havoc DMG. ", "", "", 8),
        ("6000055.webp", "Dwarf Cassowary", &["Sierra Gale","Rejuvenating Glow"], "Common", 1, "Summon a Dwarf Cassowary that tracks and attacks the enemy, dealing 38.4% Physical DMG 3 time(s). ", "", "", 8),
        ("310000250.webp", "Whiff Whaff", &["Sierra Gale","Rejuvenating Glow","Moonlit Clouds"], "Common", 1, "Summon a Whiff Whaff that triggers an air explosion, dealing 51.36% Aero DMG and produce a Low-pressure Zone. The Low-pressure Zone continuously pulls enemies nearby towards the center for 2s, dealing 19.97% Aero DMG up to 6 times. ", "", "", 15),
        ("310000250.webp", "Hooscamp", &["Sierra Gale","Lingering Tunes"], "Common", 1, "Transform into Hooscamp Flinger and pounce at the enemies, dealing 48.00%+96 Aero DMG. ", "", "", 8),
        ("310000070.webp", "Havoc Warrior", &["Celestial Light","Havoc Eclipse"], "Common", 1, "Transform into Havoc Warrior to attack up to 3 times, dealing 171.73% Havoc DMG each time.", "", "", 15),
        ("310000180.webp", "Cruisewing", &["Celestial Light","Rejuvenating Glow","Moonlit Clouds"], "Common", 1, "Summon a Cruisewing that restores HP for all current team characters by 1.80% of their Max HPs plus an additional 80 points of HP, up to 4 times. ", "", "", 8),
        ("310000090.webp", "Zig Zag", &["Celestial Light","Moonlit Clouds","Lingering Tunes"], "Common", 1, "Summon a Zig Zag that denotates Spectro energy, dealing 48%+96 Spectro DMG and creating a Stagnation Zone that lasts 1.8s. ", "", "", 15),
        ("310000110.webp", "Tick Tack", &["Havoc Eclipse","Rejuvenating Glow","Lingering Tunes"], "Common", 1, "Summon a Tick Tack that charges and bites the enemy. The charge from Tick Tack will deal 68.48% Havoc DMG to the enemy, and the bite will deal 102.72% Havoc DMG to the enemy. Reduces enemy Vibration Strength by up to 5.00% during 5s.", "", "", 15),
        ("310000260.webp", "Diamondclaw", &["Moonlit Clouds","Lingering Tunes"], "Common", 1, "Transform into Crystal Scorpion and enter a Parry State. Counterattack when the Parry State is over, dealing 48.00%+96 Physical DMG. ", "", "", 8),

        //Rinascita
        ("6000093.webp", "Golden Junkrock", &["Frosty Resolve","Eternal Radiance","Law of Harmony"], "Common", 1, "Summon a Golden Junrock that charges forward, dealing 129.60% Spectro DMG to enemies in its path.", "", "", 8),
        ("310000480.webp", "Chest Mimic", &["Frosty Resolve","Midnight Veil","Empyrean Anthem"], "Common", 1, "Summon a Chest Mimic to attack enemies with 3 consecutive strikes, each dealing 64.19% Spectro DMG.", "", "", 15),
        ("310000370.webp", "Galescourge Stalker", &["Frosty Resolve","Empyrean Anthem"], "Common", 1, "Summon a Galescourge Stalker that restores nearby party members' HP by 2.70% of their Max HP, up to 3 times.", "", "", 8),
        ("310000450.webp", "Hocus Pocus", &["Frosty Resolve","Empyrean Anthem"], "Common", 1, "Summon a Hocus Pocus to attack enemies with 3 consecutive strikes, each dealing 43.20% Havoc DMG.", "", "", 8),
        ("310000410.webp", "Chop Chop: Leftless", &["Frosty Resolve","Tidebreaking Courage"], "Common", 1, "Summon a Chop Chop: Leftless to attack enemies, dealing 129.60% Spectro DMG.", "", "", 8),
        ("310000420.webp", "Chop Chop: Rightless", &["Frosty Resolve","Tidebreaking Courage"], "Common", 1, "Summon a Chop Chop: Rightless to attack enemies, dealing 129.60% Havoc DMG.", "", "", 8),
        ("310000460.webp", "Lottie Lost", &["Frosty Resolve","Tidebreaking Courage"], "Common", 1, "Summon a Lottie Lost to attack enemies, dealing 129.60% Spectro DMG.", "", "", 8),
        ("310000390.webp", "Frostscourge Stalker", &["Eternal Radiance","Midnight Veil"], "Common", 1, "Summon a Frostscourge Stalker to attack enemies, dealing 129.60% Glacio DMG.", "", "", 8),
        ("310000430.webp", "Fae Ignis", &["Eternal Radiance","Midnight Veil","Dream of the Lost"], "Common", 1, "Summon a Fae Ignis to attack enemies, dealing 129.60% Havoc DMG.", "", "", 8),
        ("6000095.webp", "Aero Prism", &["Eternal Radiance","Tidebreaking Courage"], "Common", 1, "Summon an Aero Prism to attack enemies, dealing 19.26% Aero DMG.", "", "", 15),
        ("310000400.webp", "Chop Chop: Headless", &["Eternal Radiance","Tidebreaking Courage"], "Common", 1, "Summon a Chop Chop: Headless to attack enemies, dealing 129.60% Fusion DMG.", "", "", 8),
        ("310000470.webp", "Diggy Duggy", &["Eternal Radiance","Tidebreaking Courage"], "Common", 1, "Transform into Diggy Duggy and jump up into the air to smash onto enemies, dealing 268.20% Physical DMG", "", "", 15),
        ("6000099.webp", "Sagittario", &["Eternal Radiance","Gusts of Welkin","Flaming Clawprint"], "Common", 1, "Transform into Sagittario to move a certain distance and perform a ranged attack, dealing 268.20% Spectro DMG. Getting attacked while moving in the Sagittario form triggers form triggers a damage avoiding enhanced Dodge Counter, dealing 268.20% Spectro DMG once and 53.64% Spectro DMG 5 times.", "", "", 15),
        ("310000380.webp", "Voltscourge Stalker", &["Midnight Veil","Empyrean Anthem"], "Common", 1, "Summon a Voltscourge Stalker to perform 3 stages of attacks on enemies, each dealing 43.20% Electro DMG.", "", "", 8),
        ("310000440.webp", "Nimbus Wraith", &["Midnight Veil","Empyrean Anthem","Flamewing's Shadow"], "Common", 1, "Summon a Nimbus Wraith that restores the active Resonator's HP by 2.70% of their Max HP, up to 4 times.", "", "", 15),
        ("6000102.webp", "Electro Drake", &["Midnight Veil","Gusts of Welkin","Flaming Clawprint"], "Common", 1, "Summon an Electro Drake to attack enemies, dealing 43.20% Electro DMG 3 times.", "", "", 8),
        ("6000098.webp", "La Guardia", &["Midnight Veil","Gusts of Welkin","Flaming Clawprint"], "Common", 1, "Transform into La Guardia and attack nearby targets, dealing 268.20% Physical DMG. Hold the Echo Skill to maintain the Echo form for a while to slash enemies and cast a ranged attack forward. The slash deals 268.20% Physical DMG, and the ranged attack deals 17.87% Physical DMG up to 15 times.", "", "", 15),
        ("6000094.webp", "Calcified Junrock", &["Empyrean Anthem","Tidebreaking Courage","Crown of Valor"], "Common", 1, "Summon a Calcified Junrock that restores HP for nearby Resonators in the team by 2.52% of their Max HP, up to 5 times.", "", "", 15),
        ("6000101.webp", "Aero Drake", &["Tidebreaking Courage","Gusts of Welkin", "Windward Pilgrimage"], "Common", 1, "Summon an Aero Drake to attack enemies, dealing 129.60% Aero DMG.", "", "", 8),
        ("6000103.webp", "Glacio Drake", &["Gusts of Welkin", "Windward Pilgrimage"], "Common", 1, "Summon a Glacio Drake to attack enemies, dealing 25.92% Glacio DMG 5 times.", "", "", 8),
        ("6000110.webp", "Devotee's Flesh", &["Gusts of Welkin","Flaming Clawprint","Windward Pilgrimage"], "Common", 1, "Summon a Devotee's Flesh to attack enemies, dealing 43.20% Aero DMG 3 times.", "", "", 8),
        ("6000100.webp", "Sacerdos", &["Gusts of Welkin","Flaming Clawprint","Windward Pilgrimage"], "Common", 1, "Summon a Sacerdos to attack enemies, dealing 64.80% Aero DMG 2 times.", "", "", 8),
        ("6000108.webp", "Spectro Drake", &["Flaming Clawprint", "Windward Pilgrimage"], "Common", 1, "Summon a Spectro Drake to attack enemies, dealing 43.20% Spectro DMG 3 times.", "", "", 8),
        ("6000092.webp", "Fusion Drake", &["Flaming Clawprint", "Windward Pilgrimage"], "Common", 1, "Summon a Fusion Drake to attack enemies, dealing 25.92% Fusion DMG 3 times.", "", "", 8), //Asset from hakushin, renders nicely in the UI, so we can mix if needed.
        ("6000109.webp", "Havoc Drake", &["Flaming Clawprint", "Windward Pilgrimage", "Thread of Severed Fate"], "Common", 1, "Summon a Havoc Drake to attack enemies, dealing 129.60% Havoc DMG 3 times.", "", "", 8),
        ("6000118.webp", "Nightmare: Glacio Predator", &["Dream of the Lost"], "Common", 1, "Summon a Glacio Predator that throws an ice spear, dealing 46.08% Glacio DMG on hit. Deal 4.61% Glacio DMG up to 10 times during the charging time, and 23.04% Glacio DMG when the spear explodes.", "", "", 8),
        ("6000117.webp", "Nightmare: Havoc Warrior", &["Dream of the Lost"], "Common", 1, "Transform into Havoc Warrior to attack up to 3 times, dealing 171.73% Havoc DMG each time.", "", "", 15),
        ("6000119.webp", "Nightmare: Tambourinist", &["Dream of the Lost"], "Common", 1, "Summon a Tambourinist that plays out Melodies of Annihilation. Any Resonator on the team gains the following effect for 10s upon obtaining a Melody of Annihilation: When the Resonator hits a target, the Tambourinist deals 14.40% Havoc DMG to the target, up to 10 times.", "", "", 15),
        ("6000164.webp", "Nightmare: Aero Predator", &["Crown of Valor"], "Common", 1, "Summon an Aero Predator that throws a dart forward. The dart will bounce between enemies up to three times, dealing 28.80% Aero DMG each time it hits.", "", "", 8),
        ("6000163.webp", "Nightmare: Electro Predator", &["Crown of Valor"], "Common", 1, "Summon an Electro Predator to shoot the enemy 5 times. The first 4 shots deals 17.28% Electro DMG, and the last deals 46.08% Electro DMG.  ", "", "", 8),
        ("6000166.webp", "Nightmare: Chirpuff", &["Law of Harmony"], "Common", 1, "Summon a Chirpuff that self-inflates and blasts a powerful gust of wind forward 3 times. Each blast inflicts 38.40% Aero DMG and pushes enemies backwards. ", "", "", 8),
        ("6000165.webp", "Nightmare: Gulpuff", &["Law of Harmony"], "Common", 1, "Summon a Gulpuff that blows bubbles 5 times, each time dealing 23.04% Glacio DMG. ", "", "", 8),
        ("6000169.webp", "Nightmare: Baby Viridblaze Saurian", &["Flamewing's Shadow"], "Common", 1, "Transform into Baby Viridblaze Saurian to rest in place, and slowly restore HP.", "", "", 8),
        ("6000170.webp", "Nightmare: Baby Roseshroom", &["Flamewing's Shadow"], "Common", 1, "Summon a Baby Roseshroom that fires a laser, dealing 32.00%+64 Havoc DMG.", "", "", 8),
        ("6000172.webp", "Nightmare: Dwarf Cassowary", &["Thread of Severed Fate"], "Common", 1, "Summon a Dwarf Cassowary that tracks and attacks the enemy, dealing 38.40% Physical DMG 3 time(s).", "", "", 8),
        
        //Lahrai-Roi
        ("6000171.webp", "Nightmare: Tick Tack", &["Thread of Severed Fate"], "Common", 1, "Summon a Tick Tack that charges and bites the enemy. The charge from Tick Tack will deal 68.48% Havoc DMG to the enemy, and the bite will deal 102.72% Havoc DMG to the enemy. Reduces enemy Vibration Strength by up to 5% during 5s. ", "", "", 15),
        ("6000177.webp", "Geospider S4", &["Halo of Starry Radiance", "Pact of Neonlight Leap"], "Common", 1, "Summon a Geospider S4 to attack enemies, dealing an instance of 51.84% Spectro DMG and an instance of 77.76% Spectro DMG.", "", "", 8),
        ("6000174.webp", "Tremor Warrior", &["Halo of Starry Radiance", "Rite of Gilded Revelation"], "Common", 1, "Transform into a Tremor Warrior and viciously attack enemies in the front, dealing 205.2% Electro DMG.", "", "", 8),
        ("6000176.webp", "Mining Drone", &["Halo of Starry Radiance", "Rite of Gilded Revelation"], "Common", 1, "Transform into a Mining Drone to attack enemies, dealing 102.6% Havoc DMG twice.", "", "", 8),
        ("6000175.webp", "Flora Drone", &["Pact of Neonlight Leap", "Rite of Gilded Revelation"], "Common", 1, "Summon a Flora Drone, dealing 64.8% Aero DMG to enemies and healing Resonators within range by 3.6% of their Max HP plus an additional 160 HP.", "", "", 8),
        ("6000178.webp", "Zip Zap", &["Pact of Neonlight Leap", "Rite of Gilded Revelation"], "Common", 1, "Summon a Zip Zap to launch spinning attacks at enemies, dealing 25.92% Electro DMG 5 times.", "", "", 8),
    ]
}

/// Get all echo mappings combined
pub fn get_echo_mappings() -> HashMap<String, AssetMetadata> {
    let mut map = HashMap::new();

    let all_echoes = vec![
        get_overlord_echoes(),
        get_elite_echoes(),
        get_common_echoes(),
    ];

    for echo_list in all_echoes {
        for (filename, name, sets, class, cost, passive1, passive2, passive3, cooldown) in echo_list {
            map.insert(filename.to_string(), AssetMetadata {
                id: name.to_lowercase().replace(" ", "_").replace("'", ""),
                filename: filename.to_string(),
                display_name: name.to_string(),
                asset_type: "echo".to_string(),
                rarity: Some(cost), // Using cost as rarity for echoes
                element: Some(sets.join(", ")), // Using sets as element for echoes
                weapon_type: None,
                echo_class: Some(class.to_string()),
                cost: Some(cost),
                tags: vec![passive1.to_string(), passive2.to_string(), passive3.to_string(), format!("Cooldown: {}s", cooldown)],
            });
        }
    }

    map
}